export const topics = [
  {
    slug: 'ai-content-creation',
    title: 'AI Content Creation Tools',
    tagline: 'Everything about generating content with AI',
    description: 'Discover the best AI content creation tools for writing, blogging, and content marketing. Compare features, pricing, and real-world performance.',
    tags: ['content generation', 'content creation', 'ai writing tools', 'Content Creation', 'ai writing', 'writing tools', 'AI writing', 'Content Generation', 'AI Writing Tools', 'Content creation', 'AI writing tools'],
    keywords: 'AI content creation, AI writing tools, content generation, AI blog writing, AI copywriting',
  },
  {
    slug: 'ai-image-generation',
    title: 'AI Image Generators',
    tagline: 'Create stunning visuals with AI',
    description: 'Compare Midjourney, DALL-E 3, Stable Diffusion, and other AI image generators. Find the best tool for your creative workflow.',
    tags: ['midjourney', 'dall-e', 'stable diffusion', 'image generation', 'ai art', 'art generation', 'AI Image Generation', 'Midjourney', 'ai image generator', 'ai design'],
    keywords: 'AI image generation, Midjourney, DALL-E, Stable Diffusion, AI art',
  },
  {
    slug: 'ai-video-production',
    title: 'AI Video Tools & Production',
    tagline: 'Edit and create videos with AI',
    description: 'Explore AI-powered video editing, generation, and production tools. From Sora to Runway, find the best AI for your video workflow.',
    tags: ['ai video tools', 'sora', 'runway', 'pika', 'video creation', 'AI Video Editing', 'Video Editing Software', 'AI Video', 'Riverside', 'Descript', 'ai tools for youtube', 'AI scripts', 'youtube creator tools', 'video editing software', 'ai video generators'],
    keywords: 'AI video editing, Sora, Runway, AI video generation, YouTube AI tools',
  },
  {
    slug: 'ai-coding-tools',
    title: 'AI Coding Assistants',
    tagline: 'Write code faster with AI',
    description: 'Review and compare AI coding assistants like Cursor, GitHub Copilot, Codeium, and Claude for coding. Find the best AI pair programmer.',
    tags: ['Cursor', 'Codeium', 'Copilot', 'coding tools', 'AI code assistants', 'AI coding assistants', 'GitHub Copilot', 'Claude code', 'coding assistant', 'AI coding', 'AI development', 'Coding', 'AI code assistants'],
    keywords: 'AI coding, Cursor, Copilot, Codeium, AI pair programming',
  },
  {
    slug: 'ai-marketing-seo',
    title: 'AI for Marketing & SEO',
    tagline: 'Supercharge your marketing with AI',
    description: 'Learn how to use AI for SEO, email marketing, social media, and digital marketing. Compare top AI marketing tools and strategies.',
    tags: ['email marketing', 'social media', 'digital marketing', 'AI email marketing', 'email automation', 'SEO', 'AI for SEO', 'Keyword Research', 'Frase', 'Surfer SEO', 'Clearscope', 'AI writing', 'content marketing', 'jasper', 'copy.ai', 'Jasper', 'Writesonic', 'Copy AI', 'aitools', 'ai marketing', 'marketing automation', 'sales automation'],
    keywords: 'AI marketing, AI SEO, email marketing AI, content marketing AI',
  },
  {
    slug: 'ai-voice-audio',
    title: 'AI Voice & Music Generation',
    tagline: 'Generate speech, voiceovers, and music with AI',
    description: 'Explore AI voice generators like ElevenLabs, PlayHT, and Murf, plus AI music tools like Suno and Udio. Create professional audio with AI.',
    tags: ['elevenlabs', 'voice ai', 'text to speech', 'ai voice generators', 'ElevenLabs', 'Play HT', 'Murf', 'voice generator', 'AI voice', 'ai music generators', 'suno', 'udio', 'music production', 'AI Podcast', 'podcast tools', 'AI for podcasting', 'podcast production', 'AI music'],
    keywords: 'AI voice, ElevenLabs, Suno, Udio, text to speech, AI music',
  },
  {
    slug: 'ai-productivity-tools',
    title: 'AI Productivity & Workflow',
    tagline: 'Automate and optimize with AI',
    description: 'Discover how Notion AI, ClickUp AI, and other AI productivity tools can streamline your workflow and boost efficiency.',
    tags: ['productivity', 'Notion AI', 'ClickUp AI', 'automation', 'Workflow Automation', 'Task Management', 'Productivity', 'Productivity Tools', 'note-taking', 'project management', 'collaboration', 'efficiency software', 'productivity tools'],
    keywords: 'AI productivity, Notion AI, ClickUp AI, workflow automation',
  },
  {
    slug: 'ai-chatbots-comparison',
    title: 'AI Chatbots & Assistants',
    tagline: 'Compare the best AI chatbots',
    description: 'Side-by-side comparison of ChatGPT, Claude, Gemini, and Perplexity. Find the best AI assistant for your needs.',
    tags: ['ChatGPT', 'Claude', 'Gemini', 'Perplexity', 'AI Search', 'AI Chatbots', 'Chatbots', 'chatgpt', 'claude', 'gemini', 'comparison', 'AI models', 'GPT-4o', 'Gemini 1.5 2026', 'Claude 4'],
    keywords: 'AI chatbots, ChatGPT, Claude, Gemini, Perplexity',
  },
];
