#!/usr/bin/env node
const fs = require('fs');
const path = require('path');
require('dotenv').config({ path: path.join(__dirname, '..', '.env.local') });

const POSTS_DIR = path.join(__dirname, '..', 'content', 'posts');
const REPORTS_DIR = path.join(__dirname, '..', 'public', 'reports');
if (!fs.existsSync(REPORTS_DIR)) fs.mkdirSync(REPORTS_DIR, { recursive: true });

function getPosts() {
  return fs.readdirSync(POSTS_DIR).filter(f => f.endsWith('.mdx')).map(f => {
    const c = fs.readFileSync(path.join(POSTS_DIR, f), 'utf8');
    const get = (k) => (c.match(new RegExp(`^${k}:\\s*"?([^"\\n]*)"?`, 'm')) || [])[1] || '';
    const body = c.match(/^---\r?\n[\s\S]+?\r?\n---\r?\n([\s\S]+)$/)?.[1] || '';
    const tags = (c.match(/^tags:\s*\[([^\]]+)\]/m) || [])[1]?.split(',').map(t => t.trim().replace(/['"]/g, '')) || [];
    return {
      slug: f.replace(/\.mdx$/, ''),
      title: get('title'),
      date: get('date'),
      category: get('category'),
      tags,
      wordCount: body.trim().split(/\s+/).length,
      hasFaq: body.includes('## FAQ'),
      hasQuickAnswer: body.includes('Quick Answer'),
      hasKeyTakeaways: body.includes('Key Takeaways'),
    };
  }).filter(p => p.title);
}

(async () => {
  const posts = getPosts();

  if (posts.length === 0) {
    console.log('No posts found.');
    process.exit(0);
  }

  const categories = {};
  const tagCounts = {};
  let featuredCount = 0;
  let faqCount = 0;
  let quickAnswerCount = 0;
  let takeawayCount = 0;
  let totalWords = 0;

  for (const p of posts) {
    categories[p.category || 'Uncategorized'] = (categories[p.category || 'Uncategorized'] || 0) + 1;
    for (const t of p.tags) tagCounts[t] = (tagCounts[t] || 0) + 1;
    totalWords += p.wordCount;
    if (p.hasFaq) faqCount++;
    if (p.hasQuickAnswer) quickAnswerCount++;
    if (p.hasKeyTakeaways) takeawayCount++;
  }

  const sortedTags = Object.entries(tagCounts).sort((a, b) => b[1] - a[1]).slice(0, 20);
  const sortedCats = Object.entries(categories).sort((a, b) => b[1] - a[1]);

  const lines = [];
  lines.push('# AI Pulse Daily — Analytics Report');
  lines.push('');
  lines.push(`Generated: ${new Date().toISOString()}`);
  lines.push('');
  lines.push('---');
  lines.push('');
  lines.push('## 📊 Content Overview');
  lines.push('');
  lines.push(`- **Total posts:** ${posts.length}`);
  lines.push(`- **Total words:** ${totalWords.toLocaleString()}`);
  lines.push(`- **Avg words/post:** ${Math.round(totalWords / posts.length)}`);
  lines.push(`- **Posts with FAQ:** ${faqCount} (${Math.round(faqCount / posts.length * 100)}%)`);
  lines.push(`- **Posts with Quick Answer:** ${quickAnswerCount} (${Math.round(quickAnswerCount / posts.length * 100)}%)`);
  lines.push(`- **Posts with Key Takeaways:** ${takeawayCount} (${Math.round(takeawayCount / posts.length * 100)}%)`);
  lines.push('');
  lines.push('## 📂 Categories');
  lines.push('');
  lines.push('| Category | Count |');
  lines.push('|----------|-------|');
  for (const [cat, count] of sortedCats) {
    lines.push(`| ${cat} | ${count} |`);
  }
  lines.push('');
  lines.push('## 🏷️ Top Tags');
  lines.push('');
  lines.push('| Tag | Count |');
  lines.push('|-----|-------|');
  for (const [tag, count] of sortedTags) {
    lines.push(`| ${tag} | ${count} |`);
  }
  lines.push('');
  lines.push('## 🚀 SEO Score');
  lines.push('');
  const seoScore = Math.round((faqCount / Math.max(posts.length, 1)) * 25 + (quickAnswerCount / Math.max(posts.length, 1)) * 25 + (takeawayCount / Math.max(posts.length, 1)) * 25 + (posts.length >= 20 ? 25 : (posts.length / 20) * 25));
  lines.push(`- **SEO Readiness Score:** ${seoScore}%`);
  lines.push(`- **Goal:** 1,000,000 monthly visitors`);
  lines.push(`- **Current:** tracking via GA4 (G-PG9572RLVH)`);
  lines.push('');
  lines.push('---');
  lines.push('*Auto-generated by Analytics Agent*');

  const reportPath = path.join(REPORTS_DIR, `analytics-${new Date().toISOString().split('T')[0]}.md`);
  fs.writeFileSync(reportPath, lines.join('\n'), 'utf8');
  console.log(`✅ Report saved: ${reportPath}`);
  console.log(`   ${posts.length} posts analyzed`);
  console.log(`   SEO Score: ${seoScore}%`);
})();
